### ISSUE TITLE
Dependency no longer available

### ISSUE THREAD

**Issue by joaquinipar** [Nguyen-Hoang-Nam/immudb-elixir#7]
https://github.com/Nguyen-Hoang-Nam/immudb-elixir/blob/518665ed8c0ff5aeb42d8129070b58fe5bf3f517/mix.exs#L26

Hi, I've been trying to use your library for a personal project and I'm having a problem when executing mix deps.get, 

```* Getting immudb_elixir (https://github.com/Nguyen-Hoang-Nam/immudb-elixir.git)
remote: Enumerating objects: 82, done.        
remote: Counting objects: 100% (82/82), done.        
remote: Compressing objects: 100% (57/57), done.        
remote: Total 82 (delta 33), reused 61 (delta 20), pack-reused 0        
origin/HEAD set to main
* Getting grpc (https://github.com/Nguyen-Hoang-Nam/grpc.git)
remote: Repository not found.
fatal: repository 'https://github.com/Nguyen-Hoang-Nam/grpc.git/' not found
** (Mix) Command "git --git-dir=.git fetch --force --quiet --progress" failed```

Apparently one of the dependencies is gone, is it possible to fix it?
Thanks!

**Comment by Nguyen-Hoang-Nam** [comment]
Last month, I found that "elixir-grpc/gun" release 2.0.1 and "elixir-grpc/grpc" also updated its dependency. Therefore, I removed my fork of grpc because it seem to be useless.

I'm working in branch [immudb-1.3.1](https://github.com/Nguyen-Hoang-Nam/immudb-elixir/tree/immudb-1.3.1) which fix this issue and support new version of immudb.

Currently, you can find this package in deps directory and change this line to `{:grpc, "~> 0.5.0"},` and it should work.

For better solution, I'll release soon an updating dependency in main branch.

**Comment by Nguyen-Hoang-Nam** [comment]
I update dependencies today, it should work now.
